apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  namespace: app
  labels:
    app: calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: robertpolanski/calculator:v1
          ports:
            - containerPort: 8081