apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - calculator-deployment.yml
  - msmanager-deployment.yml
  - calculator-service.yml
  - msmanager-service.yml
