apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  namespace: {{ .Values.namespace }}
  labels:
    app: calculator
spec:
  replicas: {{ .Values.calculator.replicas }}
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: robertpolanski/calculator:0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8081