apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mssandbox
  namespace: apps
spec:
  releaseName: mssandbox
  chart:
    spec:
      chart: ./charts/mssandbox
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1m
  values:
    msmanager:
      replicas: 3
    calculator:
      replicas: 3
      url: "http://calculator:8081"
    namespace: apps
